### ISSUE TITLE
Docker 29.1.2 minimum supported API defaults to 1.44 deunhealth using 1.41

### ISSUE THREAD

**Issue by disaac** [qdm12/deunhealth#90]
With the latest docker release the API version has increased to 1.44 min. Should update deunhealth to support the latest api. 

```
2025-12-04T10:55:52-08:00 INFO [healthcheck] listening on 127.0.0.1:9999
2025-12-04T10:55:52-08:00 ERROR Error response from daemon: client version 1.41 is too old. Minimum supported API version is 1.44, please upgrade your client to a newer version
```

**Comment by disaac** [comment]
As a temporary workaround until the docker api is updated I just set my min to lower and restarted my docker service
```bash
jq '. + {"min-api-version": "1.41"}' /etc/docker/daemon.json | tee /tmp/daemon.json
mv -f /tmp/daemon.json /etc/docker/daemon.json
systemctl restart docker
```

**Comment by TJJP** [comment]
I tried that but then it said: `jq: error: Could not open file /etc/docker/daemon.json: No such file or directory`

**Comment by qdm12** [comment]
Doesn't the api negotiation pr fix solve it? If not let me know I'll bump the docker dependencies in go.mod which should fix it.

**Comment by TJJP** [comment]
@qdm12 So I realize that my fix https://github.com/qdm12/deunhealth/pull/91 does not fix this since I was using a newer version of docker that actually made it work for me when I was testing and not my fix. I think bumping docker dependencies mainly these two would fix this: 
```
	github.com/docker/docker v23.0.1+incompatible
	github.com/moby/moby v23.0.1+incompatible 
```
When I was playing around with it (not very experienced in GO so help is appreciated) I had to fix a few other errors that came with the update to the dependencies.  Looking back at the way I tried to fix it with https://github.com/qdm12/deunhealth/pull/91, I think it would be better to bump the dependencies and remove my addition of code since it would require hard coding the docker api version to actually fix the issue. Sorry for the confusion and Thanks for the help!

**Comment by qdm12** [comment]
Docker got bumped in the latest image 😉
Closing this!

**Comment by TJJP** [comment]
I am not seeing the bump in version for docker. Can you check if it went through?

**Comment by TJJP** [comment]
I see it now and deunhealth is monitoring correctly now!

**Comment by qdm12** [comment]
Yes sorry I forgot to push the code, shame shame shame 😄 merry xmas! 🎄
